### ISSUE TITLE
Add Login & Register components to ReactJS generator  

### ISSUE THREAD

**Issue by aeksco** [codotype/codotype-generator#46]
See attached screenshots for requirements:

![screenshot from 2018-07-23 15-50-12](https://user-images.githubusercontent.com/4616233/43099420-245e24be-8e90-11e8-84b8-39b170522b15.png)
![screenshot from 2018-07-23 15-50-03](https://user-images.githubusercontent.com/4616233/43099421-2468eb2e-8e90-11e8-980b-44b4729241a4.png)

**Comment by aeksco** [comment]
Add `POST` API calls with Axios to the following endpoints:
`/api/auth/login`
`/api/auth/register`

**Comment by aeksco** [comment]
Partially resolved by #48 - the Login and Register forms must still be wired up to the React component's `<input>` elements

**Comment by sjhuang26** [comment]
Why is this still in progress?

**Comment by aeksco** [comment]
Resolved
