### ISSUE TITLE
ReactJS - Research React + Bootstrap component libraries for things like Modals & Tooltips

### ISSUE THREAD

**Issue by aeksco** [codotype/codotype-generator#63]
Leave some comments here with a few links to some potential options :)

**Comment by sjhuang26** [comment]
[https://www.npmjs.com/package/react-bootstrap4-modal](https://www.npmjs.com/package/react-bootstrap4-modal)
I like this library because it's very simple but still effective.

**Comment by aeksco** [comment]
Closing this issue - moving it into the [codotype-react-generator](https://github.com/codotype/codotype-react-generator) library
