### ISSUE TITLE
Flask - Generate models to interface the API with MongoDB

### ISSUE THREAD

**Issue by aeksco** [codotype/codotype-generator#66]
[An example boilerplate](https://github.com/esfoobar/flask-mongodb-boilerplate)

@ericharmeling Let's talk about this one soon - the generator logic won't be terribly complicated, but you'll need a MongoDB instance running locally to connect to your Flask app. 

I'll post some more example code in this issue to help guide your work :)

**Comment by aeksco** [comment]
@ericharmeling Take a look at the [gothinkster/flask-realworld-example-app](https://github.com/gothinkster/flask-realworld-example-app) - they pretty much nailed it. I think going forward we'll be using a lot of their example applications to act as a starter for new blazeplate generators - removes a lot of the legwork from our end :)

**Comment by ericharmeling** [comment]
@aeksco Looks great 💯 !

I'll go over gothinksters example and start working on a "prototype" for the Flask API.

**Comment by aeksco** [comment]
Closing this issue - moving it into the [codotype-flask-postgresql-generator](https://github.com/codotype/codotype-flask-postgresql-generator) repository
